CREATE DATABASE IF NOT EXISTS `matdegy2024_1`;
USE matdegy2024_1;

CREATE TABLE IF NOT EXISTS `users` (
  `uid` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `nickname` varchar(20) NOT NULL UNIQUE,
  `code` INT(8) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `problems` (
  `pid` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `number` INT NOT NULL,
  `title` varchar(100) NOT NULL,
  `answer` varchar(100)
);

CREATE TABLE IF NOT EXISTS `solve` (
  `uid` INT NOT NULL,
  `pid` INT NOT NULL,
  `time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `elapsed_time` INT NOT NULL,
  PRIMARY KEY (`uid`, `pid`)
);

CREATE TABLE IF NOT EXISTS `api_log` (
  `lid` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `log` TEXT NOT NULL,
  `time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
